name: Clean OS

on:
  pull_request:
    branches: [ "master", "develop" ]
    types: [ closed ]

env:
  APPLICATION_NAME: "front-article-store-test"

jobs:
  clean-os:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare branch name
        uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ github.head_ref }}
          separator: "/"
          maxsplit: -1

      - name: Prepare tags
        id: meta
        run: |
          echo "::set-output name=version::${{ steps.branch.outputs._1 || steps.branch.outputs._0 }}"

      #       DEPLOY
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Add OS host to resolv.conf
        run: |
          sudo mv /etc/resolv.conf /etc/resolv1.conf
          cat /etc/resolv1.conf | sudo tee -a /etc/resolv.conf
          echo "nameserver ${{ secrets.DNS_IP }}" | sudo tee -a /etc/resolv.conf

      - name: Log in to OpenShift
        run: |
          oc login -u ${{ secrets.LOGIN_OS }} -p ${{ secrets.PASSWORD_OS }} --server=https://${{ secrets.OPENSHIFT_SERVER }}:6443 --insecure-skip-tls-verify
          oc project ${{ env.OS_PROJECT }}

      - run: oc whoami

      - name: Delete
        run: |
          oc delete all -l app=${{ env.APPLICATION_NAME }}-${{ steps.meta.outputs.version }}

      - name: Logout from OpenShift
        run: oc logout
